import { Component } from '@angular/core';

@Component({
  selector: 'app-left-bar-job',
  templateUrl: './left-bar-job.component.html',
  styleUrls: ['./left-bar-job.component.css']
})
export class LeftBarJobComponent {
   jobs: string[] = [
    "Accounting/Auditing/Tax",
    "Administrative/Clerical",
    "Advertising/Promotion/PR",
    "Airlines/Tourism",
    "Arts/Creative Design",
    "Auditing",
    "Auto/Automotive",
    "Banking",
    "Chemical/Biochemical",
    "Civil/Construction",
    "Consulting",
    "Customer Service",
    "Doctors/Nurses",
    "Electrical/Electronics",
    "Environment/Waste Services",
    "Event",
    "Export-Import",
    "Finance/Investment",
    "FMCG",
    "Food & Beverage",
    "Food Tech/Nutrionist",
    "Freight/Logistics",
    "Freight/Logistics/Warehouse",
    "High Technology",
    "Household/Personal Care",
    "Human Resources",
    "HVAC",
    "Import/Export",
    "Industrial Products",
    "Internet/Online Media",
    "Interpreter/Translator",
    "IT - Hardware/Networking",
    "IT - Software",
    "Law/Legal Services",
    "Library",
    "Maintenance",
    "Manufacturing/Process",
    "Marine",
    "Marketing",
    "Mechanical",
    "Mechanical/Auto/Automotive",
    "Medical/Healthcare",
    "Merchandising/Purchasing/Supply Chain",
    "NGO/Non-profit",
    "Online Marketing",
    "Pharmaceutical Representatives",
    "Planning/Projects",
    "Printing/Publishing",
    "Production/Process",
    "Purchasing/Merchandising",
    "Quality Control (QA/QC)",
    "Real Estate",
    "Restaurant/Hotel",
    "Retail/Wholesale",
    "Sales Technical",
    "Sales/Business Development",
    "Securities & Trading",
    "Security (Guard)",
    "Statistics",
    "Telecommunications",
    "Textiles/Garments/Fashion",
    "TV/Media/Newspaper/Editor"
  ];


}
